### ISSUE TITLE
AttributeError: 'MultirotorClient' object has no attribute 'getPosition'

### ISSUE THREAD

**Issue by majingchunn** [jzstudent/UAV-auto-navigation-and-object-tracking-based-on-RL#11]
D:\anaconda3\anaconda3installation\envs\yolov5\python.exe D:\ue_installer\airlearning-ue4-master2\airsim_rl\SAC.py 
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Traceback (most recent call last):
  File "D:\ue_installer\airlearning-ue4-master2\airsim_rl\SAC.py", line 676, in <module>
    sac(device=device)
  File "D:\ue_installer\airlearning-ue4-master2\airsim_rl\SAC.py", line 401, in sac
    env = AirSimEnv(need_render=False)
  File "D:\ue_installer\airlearning-ue4-master2\airsim_rl\gym_airsim\envs\AirGym.py", line 49, in __init__
    self.prev_state = self.init_state_f()
  File "D:\ue_installer\airlearning-ue4-master2\airsim_rl\gym_airsim\envs\AirGym.py", line 80, in init_state_f
    now = self.airgym.drone_pos()[:2]
  File "D:\ue_installer\airlearning-ue4-master2\airsim_rl\gym_airsim\envs\airlearningclient.py", line 100, in drone_pos
    x = self.client.getPosition().x_val
AttributeError: 'MultirotorClient' object has no attribute 'getPosition'

**Comment by vwbk** [comment]
I also encountered the same problem. Have you solved it？Thank you!
