### ISSUE TITLE
python  client.py 的相对导入问题

### ISSUE THREAD

**Issue by xiaoToby** [jzstudent/UAV-auto-navigation-and-object-tracking-based-on-RL#9]
(ad_py37) D:\UAV-auto-navigation-and-object-tracking-based-on-RL-main>D:/anaconda/envs/ad_py37/python.exe d:/UAV-auto-navigation-and-object-tracking-based-on-RL-main/airsim_rl/misc/move_to_airsim/client.py
Traceback (most recent call last):
  File "d:/UAV-auto-navigation-and-object-tracking-based-on-RL-main/airsim_rl/misc/move_to_airsim/client.py", line 9, in <module>
    from .utils import *
ImportError: attempted relative import with no known parent package

(ad_py37) D:\UAV-auto-navigation-and-object-tracking-based-on-RL-main>D:/anaconda/envs/ad_py37/python.exe d:/UAV-auto-navigation-and-object-tracking-based-on-RL-main/airsim_rl/misc/move_to_airsim/client.py
Traceback (most recent call last):
  File "d:/UAV-auto-navigation-and-object-tracking-based-on-RL-main/airsim_rl/misc/move_to_airsim/client.py", line 11, in <module>
    from .types import *
ImportError: attempted relative import with no known parent package

**Comment by xiaoToby** [comment]
windows 10 
python 3.7

**Comment by super-NOV-a** [comment]
sys.path.append("E:\\UAV-auto-navigation-and-object-tracking-based-on-RL\\airsim_rl\\")
from utils import *
from misc.move_to_airsim.types import *

I tried the code above, and it worked, hope it can help.

**Comment by jzstudent** [comment]
检查下move_to_airsim 文件哈

**Comment by majingchunn** [comment]
> sys.path.append（“E：\UAV-auto-navigation-and-object-tracking-based-on-RL\airsim_rl\”） from utils import * from misc.move_to_airsim.types import *
> 
> 我尝试了上面的代码，它起作用了，希望它能有所帮助。

Could you please tell me exactly where this code is added to run？

**Comment by majingchunn** [comment]
![Uploading 1.png…]()
